### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PlanningModel

### ISSUE THREAD

**Issue by zhangqiangbing** [jchengai/planTF#25]
Hi,
I download the trained model, like this:
<img width="205" alt="image" src="https://github.com/user-attachments/assets/4f497b53-2434-4745-b311-7d0ceed288b2">
Then I run the command: **sh ./script/plantf_single_scenarios.sh**
but failed,

`sh ./script/plantf_single_scenarios.sh
/mnt/data/anaconda3/envs/pluto2/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py:213: UserWarning: provider=hydra.searchpath in main, path=config/simulation is not available.
  warnings.warn(
Global seed set to 0
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback...
INFO:nuplan.planning.script.builders.main_callback_builder:Building MultiMainCallback: 4...DONE!
2024-08-14 15:30:37,936 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/worker_pool_builder.py:19}  Building WorkerPool...
2024-08-14 15:30:37,937 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py:101}  Worker: Sequential
2024-08-14 15:30:37,938 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py:102}  Number of nodes: 1
Number of CPUs per node: 1
Number of GPUs per node: 0
Number of threads across all nodes: 1
2024-08-14 15:30:37,938 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/worker_pool_builder.py:27}  Building WorkerPool...DONE!
2024-08-14 15:30:37,938 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:32}  Building experiment folders...
2024-08-14 15:30:37,938 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:35}  

        Folder where all results are stored: /mnt/data/nuplan/exp/exp/simulation/closed_loop_nonreactive_agents/2024.08.14.15.30.35

2024-08-14 15:30:37,941 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/folder_builder.py:70}  Building experiment folders...DONE!
2024-08-14 15:30:37,941 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_callback_builder.py:52}  Building AbstractCallback...
2024-08-14 15:30:37,941 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_callback_builder.py:68}  Building AbstractCallback: 0...DONE!
2024-08-14 15:30:37,941 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:47}  Building simulations...
2024-08-14 15:30:37,942 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:53}  Extracting scenarios...
2024-08-14 15:30:37,942 INFO {/mnt/data/LM/nuplan-devkit/nuplan/common/utils/distributed_scenario_filter.py:83}  Building Scenarios in mode DistributedMode.SINGLE_NODE
2024-08-14 15:30:37,942 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/scenario_building_builder.py:18}  Building AbstractScenarioBuilder...
2024-08-14 15:30:37,968 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/scenario_building_builder.py:21}  Building AbstractScenarioBuilder...DONE!
2024-08-14 15:30:37,968 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py:35}  Building ScenarioFilter...
2024-08-14 15:30:37,970 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/scenario_filter_builder.py:44}  Building ScenarioFilter...DONE!
2024-08-14 15:30:37,975 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:74}  Building metric engines...
2024-08-14 15:30:38,345 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:76}  Building metric engines...DONE
2024-08-14 15:30:38,345 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:80}  Building simulations from 1 scenarios...
2024-08-14 15:30:39,412 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/builders/simulation_builder.py:133}  Building simulations...DONE!
2024-08-14 15:30:39,412 INFO {/mnt/data/LM/planTF/run_simulation.py:94}  Running simulation...
2024-08-14 15:30:39,412 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/script/utils.py:138}  Executing runners...
2024-08-14 15:30:39,412 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:82}  Starting 1 simulations using Sequential!
2024-08-14 15:30:39,412 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/utils/multithreading/worker_pool.py:116}  Submitting 1 tasks!
2024-08-14 15:30:39,575 WARNING {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:32}  ----------- Simulation failed: with the following trace:
Sequential:   0%|                                                                                                         | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 99, in run
    self._initialize()
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 48, in _initialize
    self.planner.initialize(self._simulation.initialize())
  File "/mnt/data/LM/planTF/src/planners/imitation_planner.py", line 75, in initialize
    self._planner.load_state_dict(tmp)
  File "/mnt/data/anaconda3/envs/pluto2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlanningModel:
        Unexpected key(s) in state_dict: "agent_encoder.history_encoder.levels.0.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.0.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.1.attn.rpb". 
2024-08-14 15:30:39,576 WARNING {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:34}  Simulation failed with error:    
 Error(s) in loading state_dict for PlanningModel:
        Unexpected key(s) in state_dict: "agent_encoder.history_encoder.levels.0.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.0.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.1.attn.rpb". 
2024-08-14 15:30:39,576 WARNING {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:38}                                   
Failed simulation [log,token]:
 [2021.05.25.12.30.39_veh-25_00321_01196, 8de10fd86b825304]

2024-08-14 15:30:39,576 WARNING {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:40}  ----------- Simulation failed!   
2024-08-14 15:30:39,577 WARNING {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:123}  Failed Simulation.              
 'Traceback (most recent call last):
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 99, in run
    self._initialize()
  File "/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 48, in _initialize
    self.planner.initialize(self._simulation.initialize())
  File "/mnt/data/LM/planTF/src/planners/imitation_planner.py", line 75, in initialize
    self._planner.load_state_dict(tmp)
  File "/mnt/data/anaconda3/envs/pluto2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlanningModel:
        Unexpected key(s) in state_dict: "agent_encoder.history_encoder.levels.0.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.0.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.1.attn.rpb". 
'
2024-08-14 15:30:39,578 INFO {/mnt/data/LM/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:127}  Number of successful simulations: 0`

**It seems the model and checkpoint file not match. How could I fix it? thx**

**Comment by happy-yan** [comment]
我遇到了同样的问题，想请教一下如何解决的呢？

**Comment by happy-yan** [comment]
Unexpected key(s) in state_dict: "agent_encoder.history_encoder.levels.0.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.0.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.1.blocks.1.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.0.attn.rpb", "agent_encoder.history_encoder.levels.2.blocks.1.attn.rpb".

**Comment by happy-yan** [comment]
是torch版本问题嘛？
