### ISSUE TITLE
RuntimeError in closed_loop_nonreactive_agents/ closed_loop_reactive_agents evaluation.

### ISSUE THREAD

**Issue by sgNicola** [jchengai/planTF#33]
When I run the evaluation script for the downloaded plantf.ckpt: `sh ./script/plantf_benchmarks.sh val14` , there will be runtime error for closed_loop evaluation:

'2024-12-30 13:54:45,283 WARNING {/home/sgwang/nuplan-devkit/nuplan/planning/simulation/runner/executor.py:123}  Failed Simulation.
 'Traceback (most recent call last):
  File "/home/sgwang/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
    return sim_runner.run()
  File "/home/sgwang/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 113, in run
    trajectory = self.planner.compute_trajectory(planner_input)
  File "/home/sgwang/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 108, in compute_trajectory
    raise e
  File "/home/sgwang/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 105, in compute_trajectory
    trajectory = self.compute_planner_trajectory(current_input)
  File "/home/sgwang/planTF/src/planners/imitation_planner.py", line 116, in compute_planner_trajectory
    local_trajectory = self._planning(current_input)
  File "/home/sgwang/planTF/src/planners/imitation_planner.py", line 101, in _planning
    out = self._planner.forward(planner_feature_torch.data)
  File "/home/sgwang/planTF/src/models/planTF/planning_model.py", line 117, in forward
    x_polygon = self.map_encoder(data)
  File "/home/sgwang/data/tmp/envs/plantf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sgwang/planTF/src/models/planTF/modules/map_encoder.py", line 57, in forward
    x_polygon = self.polygon_encoder(polygon_feature, valid_mask).view(bs, M, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [1, 0, -1] because the unspecified dimension size -1 can be any value and is ambiguous'

However, it does not occur in open loop boxes.

**Comment by sgNicola** [comment]
I tried to log the polygon_feature.shape and found out that it was polygon_feature shape: torch.Size([0, 20, 6]) after several frames. But when I tested the evaluation on another machine, this RuntimeError did not occur again.

**Comment by matren12138** [comment]
Have you fixed the problem? I ran into same error

**Comment by Xiawenlong-bug** [comment]
Have you fixed the problem? I ran into same error

**Comment by yu-chen777** [comment]
Have you fixed the problem? I ran into same error
